### ISSUE TITLE
Chromium weird bug when leaving full screen

### ISSUE THREAD

**Issue by theobch** [maximbaz/chromium-vaapi-bin#3]
Hi,
Actually using the latest version of chromium (`chromium-vaapi-bin 67.0.3396.62-1` + `chromium-widevine 1:1.4.9.1088-1`), I've a bug when leaving full screen (either a full screen video or chromium itself in full screen). As an image worth more than million words, [here a screenshot](https://imgur.com/a/qPHGuUe)

Actually here what's happen: when leaving full screen mode, tabs can't put themselves back at the top of the screen, and they are mixed with the address bar.

This bug doesn't (seem to) occur with Opera and Firefox, but with Chrome and Chromium, yes. 
Here my setup:
OS: Arch Linux
Kernel: `linux 4.16.13-1`
Xorg: `xorg-server 1.20.0-5`
WM: `i3-wm 4.15-1`
Compositor: `compton 0.1_beta2.5-11`, launched with the following command:
`compton -f --backend xrender`

I've tried the following tests:
- Xorg without compton, just i3 : bug still occurs
- Xorg with compton and openbox as WM : bug still occurs
- Xorg without compton and openbox as WM : bug still occurs
- Wayland with Sway as WM : bug still occurs

Video hardware acceleration is configured well, with the help of the ArchLinux [guide](https://wiki.archlinux.org/index.php/Hardware_video_acceleration).

**Comment by maximbaz** [comment]
Hi, I have the same issue for a long time. What chromium flags do you use? In my case, it happens because I use chromium flag `--disable-gpu-driver-bug-workarounds`, do you have it enabled too?

I enable this flag because otherwise chromium sometimes hangs when playing videos in full screen, for me the broken tabs is the price of having smooth full screen videos.

I actually don't know where to complain about fixing this issue, since it can only be reproduced when using a vaapi patch (which is not merged yet) and having enabled a flag that literally says "disable GPU bugs workarounds" 😄

**Comment by theobch** [comment]
Thanks a lot, it works :D !
