### ISSUE TITLE
New update causes a distorted picture on amdgpu

### ISSUE THREAD

**Issue by biswasab** [maximbaz/chromium-vaapi-bin#4]
Not sure which vaapi patch you're using. On enabling vaapi on the latest build, causes a distorted video with reddish marks. screenshot : https://ibb.co/f3frDT

Tested with both amd gpus that I have (RX500 series and R5 series)

**Comment by maximbaz** [comment]
The patch is [this one](https://chromium-review.googlesource.com/c/chromium/src/+/532294), although I take it from [inox repo](https://github.com/gcarq/inox-patchset/) because they are adapted for stable releases.

Usually you would have a better luck posting questions [here](https://aur.archlinux.org/packages/chromium-vaapi) or [here](https://aur.archlinux.org/packages/chromium-vaapi-bin), because there are lots of people with different GPUs who might help you. I ask questions myself there 🙂

But a very similar screenshot to yours was posted recently on [chromium-vaapi-bin AUR page](https://aur.archlinux.org/packages/chromium-vaapi-bin), and someone posted this as a solution:

> digitalone commented on 2018-04-13 16:19
> It works with latest mesa packages adding 'allow_rgb10_configs=false' into /etc/environment.

If this doesn't help, I suggest you write there asking for help 🙂

**Comment by biswasab** [comment]
Oh thanks!!!
